// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/airports": {
            "get": {
                "description": "Retrieve a list of all airports from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "airports"
                ],
                "summary": "Get all airports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Airport city",
                        "name": "city",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Airport"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/airports/{airport_code}/inbound-schedule": {
            "get": {
                "description": "Retrieves the inbound flight schedule for a specified airport",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "airports"
                ],
                "summary": "Get inbound schedule for an airport",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Airport code",
                        "name": "airport_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.FlightSchedule"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing or invalid airport code",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/airports/{airport_code}/outbound-schedule": {
            "get": {
                "description": "Retrieves the outbound flight schedule for a specified airport",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "airports"
                ],
                "summary": "Get outbound schedule for an airport",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Airport code",
                        "name": "airport_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.FlightSchedule"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing or invalid airport code",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/bookings/{guid}": {
            "put": {
                "description": "Idempotent booking of flights with a GUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Book a route",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GUID",
                        "name": "guid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Booking data",
                        "name": "booking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.BookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Existing or new tickets",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.TicketFlight"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cities": {
            "get": {
                "description": "Retrieve a list of all cities from the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cities"
                ],
                "summary": "Get all cities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Airport": {
            "type": "object",
            "properties": {
                "airport_code": {
                    "type": "string"
                },
                "airport_name": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "main.BookingRequest": {
            "type": "object",
            "properties": {
                "fare_conditions": {
                    "type": "string"
                },
                "flight_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "passanger": {
                    "type": "string"
                }
            }
        },
        "main.FlightSchedule": {
            "type": "object",
            "properties": {
                "day_of_week": {
                    "type": "string"
                },
                "flight_no": {
                    "type": "string"
                },
                "origin_airport": {
                    "type": "string"
                },
                "time_of_arrival": {
                    "type": "string"
                }
            }
        },
        "main.TicketFlight": {
            "type": "object",
            "properties": {
                "fare_conditions": {
                    "type": "string"
                },
                "flight_id": {
                    "type": "integer"
                },
                "ticket_no": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Airflight Service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
