basePath: /
definitions:
  main.Airport:
    properties:
      airport_code:
        type: string
      airport_name:
        type: string
      city:
        type: string
      timezone:
        type: string
    type: object
  main.FlightSchedule:
    properties:
      day_of_week:
        type: string
      flight_no:
        type: string
      origin_airport:
        type: string
      time_of_arrival:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  title: Airflight Service API
  version: "1.0"
paths:
  /airports:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all airports from the database
      parameters:
      - description: Airport city
        in: query
        name: city
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Airport'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all airports
      tags:
      - airports
  /airports/inbound-schedule/{airport_code}:
    get:
      description: Retrieves the inbound flight schedule for a specified airport
      parameters:
      - description: Airport code
        in: path
        name: airport_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.FlightSchedule'
            type: array
        "400":
          description: Missing or invalid airport code
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get inbound schedule for an airport
      tags:
      - airports
  /airports/outbound-schedule/{airport_code}:
    get:
      description: Retrieves the outbound flight schedule for a specified airport
      parameters:
      - description: Airport code
        in: path
        name: airport_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.FlightSchedule'
            type: array
        "400":
          description: Missing or invalid airport code
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get outbound schedule for an airport
      tags:
      - airports
  /cities:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all cities from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all cities
      tags:
      - cities
swagger: "2.0"
