basePath: /
definitions:
  main.Airport:
    properties:
      airport_code:
        type: string
      airport_name:
        type: string
      city:
        type: string
      timezone:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  title: Airflight Service API
  version: "1.0"
paths:
  /airports:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all airports from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Airport'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all airports
      tags:
      - airports
  /cities:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all cities from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all cities
      tags:
      - cities
swagger: "2.0"
