basePath: /
definitions:
  main.Airport:
    properties:
      code:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  title: Airflight Service API
  version: "1.0"
paths:
  /airports:
    post:
      consumes:
      - application/json
      description: Creates a new airport with provided code and name
      parameters:
      - description: Airport data
        in: body
        name: airport
        required: true
        schema:
          $ref: '#/definitions/main.Airport'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Airport'
        "400":
          description: Invalid input
          schema:
            type: string
      summary: Create a new airport
      tags:
      - airports
swagger: "2.0"
